// This file is autogenerated. Changes will be overwritten.
#include "VJIZ3MDCXP/moc_NightModeController.cpp"
#include "VJIZ3MDCXP/moc_brightness.cpp"
#include "VJIZ3MDCXP/moc_brtbackend.cpp"
#include "VJIZ3MDCXP/moc_gpioreader.cpp"
#include "VJIZ3MDCXP/moc_lightsensor.cpp"
